on:
  issue_comment:
    types: [created]
name: Commands
jobs:
  style:
    if: startsWith(github.event.comment.body, '/style')
    name: style
    runs-on: ubuntu-latest
    steps:
      - name: Install pip
        run: |
          sudo apt update
          sudo apt install python3-pip
          sudo apt install black

      - uses: actions/checkout@v2
      - name: Initialize pip
        run: |
          pip3 install black
      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run yarn 
        run: black '**/*.{css,js,html,py}'

      - name: commit
        run: |
          git add \*.css \*.html \*.js \*.py
          git config --global user.email "bot@example.com"
          git config --global user.name "Bot"
          if [[ $(git diff --name-only --cached) != "" ]]; then  git commit -m 'automated syle update' ; fi
      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}